### ISSUE TITLE
Measurements of all the metrics

### ISSUE THREAD

**Issue by dormaayan** [sealuzh/lightweight-effectiveness#2]
Hey,

Thanks for sharing this wonderful tool - it was super helpful to use it for measuring the mutation score of other projects as well.
Do you plan to share the code of measuring all the other metrics as well or at least a full documentation of how did you use all the other tools for measuring the other metrics? It will be really helpful to reproduce your results on different code repositories.

Many thanks!

**Comment by giograno** [comment]
Hi there. I just included [here](https://github.com/sealuzh/lightweight-effectiveness/tree/master/metrics-api-usage) some code that allows the computation of the metrics.

**Comment by dormaayan** [comment]
Thanks @giograno!
 While following your instructions I get the following:

'Could not resolve dependencies for project org.example:metrics-api-usage:jar:1.0-SNAPSHOT: Failure to find raykernel.apps.readability:raykernel.apps.readability:jar:1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced'

I tried to added the jar from [here](http://www.arrestedcomputing.com/readability) but it doesn't seem to work either, do you have any idea what exactly should I install?

Dor

**Comment by giograno** [comment]
@dormaayan did you manage to solve your issue? I received I notification but I don't find your post anymore.

**Comment by dormaayan** [comment]
Hey @giograno,

For computing BUSWEIMER, it seems like the tool uses a jar which is not available: `raykernel.apps.readability.jar`
Do you have this jar, I couldn't find it online?

**Comment by giograno** [comment]
Hi @dormaayan, you can find that jar at [this](http://www.arrestedcomputing.com/readability) link.
Anyway, I've updated the project such that all the dependencies are now available. You can just try out again (just run the commands in the README) and let me know if you face any issue.
Thanks.
